import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ja' | 'zh';

export interface LanguageContextType {
  lang: LanguageCode;
  setLang: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    'nav.all_tools': 'All PDF Tools',
    'nav.merge': 'Merge PDF',
    'nav.split': 'Split PDF',
    'nav.compress': 'Compress PDF',
    'nav.convert': 'Convert PDF',
    'nav.edit_sign': 'Edit & Sign',
    'nav.security': 'Security',
    'nav.history': 'History & Stats',
    'nav.vault': 'Cloud Vault',
    'nav.login': 'Log in',
    'nav.signup': 'Sign up',
    'hero.title': 'Every tool you need to work with PDFs in one place',
    'hero.subtitle': 'Every tool you need to use PDFs, at your fingertips. All are 100% FREE and easy to use! Merge, split, compress, convert, rotate, unlock and watermark PDFs with just a few clicks.',
    'hero.privacy_note': '🔒 100% Client-Side Privacy: Your documents stay in your browser by default.',
    'hero.search_placeholder': 'Search any PDF tool (e.g. merge, compress, sign, watermark)...',
    'category.all': 'All Tools',
    'category.organize': 'Organize PDF',
    'category.optimize': 'Optimize PDF',
    'category.convert_to': 'Convert to PDF',
    'category.convert_from': 'Convert from PDF',
    'category.edit_sign': 'Edit & Sign',
    'category.security': 'PDF Security',
    'btn.select_files': 'Select PDF files',
    'btn.select_images': 'Select images',
    'btn.drop_files': 'or drop PDFs here',
    'btn.sample_pdf': 'Try with Sample PDF',
    'btn.download': 'Download PDF',
    'btn.download_zip': 'Download ZIP',
    'btn.save_vault': 'Save to Cloud Vault',
    'btn.copy_link': 'Copy Share Link',
    'btn.continue_with': 'Continue in another tool',
    'status.processed_locally': 'Processed on your device',
    'status.ready_download': 'Your PDF has been processed successfully!',
    'footer.disclaimer': 'Privacy First: We do not retain, inspect, or sell your documents. Temporary processing files are automatically cleared.',
  },
  es: {
    'nav.all_tools': 'Todas las herramientas',
    'nav.merge': 'Unir PDF',
    'nav.split': 'Dividir PDF',
    'nav.compress': 'Comprimir PDF',
    'nav.convert': 'Convertir PDF',
    'nav.edit_sign': 'Editar y Firmar',
    'nav.security': 'Seguridad',
    'nav.history': 'Historial',
    'nav.vault': 'Bóveda Cloud',
    'nav.login': 'Iniciar sesión',
    'nav.signup': 'Registrarse',
    'hero.title': 'Todas las herramientas para trabajar con PDF en un solo lugar',
    'hero.subtitle': 'Herramientas PDF 100% gratuitas y fáciles de usar. Une, divide, comprime, convierte, rota y firma tus documentos.',
    'hero.privacy_note': '🔒 Privacidad total: Tus archivos se procesan en tu propio navegador.',
    'hero.search_placeholder': 'Buscar herramienta (ej. unir, comprimir, firmar)...',
    'category.all': 'Todas',
    'category.organize': 'Organizar PDF',
    'category.optimize': 'Optimizar',
    'category.convert_to': 'Convertir a PDF',
    'category.convert_from': 'Convertir de PDF',
    'category.edit_sign': 'Editar y Firmar',
    'category.security': 'Seguridad PDF',
    'btn.select_files': 'Seleccionar archivos PDF',
    'btn.select_images': 'Seleccionar imágenes',
    'btn.drop_files': 'o arrastra los archivos aquí',
    'btn.sample_pdf': 'Probar con PDF de ejemplo',
    'btn.download': 'Descargar PDF',
    'btn.download_zip': 'Descargar ZIP',
    'btn.save_vault': 'Guardar en Bóveda',
    'btn.copy_link': 'Copiar enlace',
    'btn.continue_with': 'Continuar con otra herramienta',
    'status.processed_locally': 'Procesado en tu dispositivo',
    'status.ready_download': '¡Tu archivo PDF ha sido procesado con éxito!',
    'footer.disclaimer': 'Privacidad primero: No guardamos ni vendemos tus documentos.',
  },
  fr: {
    'nav.all_tools': 'Tous les outils PDF',
    'nav.merge': 'Fusionner PDF',
    'nav.split': 'Diviser PDF',
    'nav.compress': 'Compresser PDF',
    'nav.convert': 'Convertir PDF',
    'nav.edit_sign': 'Modifier et Signer',
    'nav.security': 'Sécurité',
    'nav.history': 'Historique',
    'nav.vault': 'Coffre Cloud',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    'hero.title': 'Tous les outils nécessaires pour vos PDF au même endroit',
    'hero.subtitle': 'Outils PDF 100% gratuits et simples à utiliser. Fusionnez, divisez, compressez et signez vos PDF.',
    'hero.privacy_note': '🔒 Confidentialité garantie: Traitement local directement dans votre navigateur.',
    'hero.search_placeholder': 'Rechercher un outil PDF...',
    'category.all': 'Tous les outils',
    'category.organize': 'Organiser PDF',
    'category.optimize': 'Optimiser',
    'category.convert_to': 'Convertir en PDF',
    'category.convert_from': 'Convertir depuis PDF',
    'category.edit_sign': 'Modifier & Signer',
    'category.security': 'Sécurité PDF',
    'btn.select_files': 'Sélectionner des fichiers PDF',
    'btn.select_images': 'Sélectionner des images',
    'btn.drop_files': 'ou déposez les fichiers ici',
    'btn.sample_pdf': 'Essayer avec un PDF exemple',
    'btn.download': 'Télécharger le PDF',
    'btn.download_zip': 'Télécharger le ZIP',
    'btn.save_vault': 'Enregistrer dans le coffre',
    'btn.copy_link': 'Copier le lien',
    'btn.continue_with': 'Continuer avec un autre outil',
    'status.processed_locally': 'Traité localement sur votre appareil',
    'status.ready_download': 'Votre PDF a été traité avec succès !',
    'footer.disclaimer': 'Confidentialité totale : vos documents ne quittent pas votre session.',
  },
  de: {
    'nav.all_tools': 'Alle PDF-Werkzeuge',
    'nav.merge': 'PDF zusammenfügen',
    'nav.split': 'PDF teilen',
    'nav.compress': 'PDF komprimieren',
    'nav.convert': 'PDF konvertieren',
    'nav.edit_sign': 'Bearbeiten & Signieren',
    'nav.security': 'Sicherheit',
    'nav.history': 'Verlauf',
    'nav.vault': 'Cloud-Tresor',
    'nav.login': 'Anmelden',
    'nav.signup': 'Registrieren',
    'hero.title': 'Alle Werkzeuge für Ihre PDF-Dateien an einem Ort',
    'hero.subtitle': '100% kostenlose, benutzerfreundliche PDF-Tools.',
    'hero.privacy_note': '🔒 100% lokaler Datenschutz im Browser.',
    'hero.search_placeholder': 'Werkzeug suchen...',
    'category.all': 'Alle Werkzeuge',
    'category.organize': 'PDF organisieren',
    'category.optimize': 'Optimieren',
    'category.convert_to': 'In PDF umwandeln',
    'category.convert_from': 'Aus PDF umwandeln',
    'category.edit_sign': 'Bearbeiten & Signieren',
    'category.security': 'PDF-Sicherheit',
    'btn.select_files': 'PDF-Dateien auswählen',
    'btn.select_images': 'Bilder auswählen',
    'btn.drop_files': 'oder Dateien hier ablegen',
    'btn.sample_pdf': 'Mit Beispiel-PDF testen',
    'btn.download': 'PDF herunterladen',
    'btn.download_zip': 'ZIP herunterladen',
    'btn.save_vault': 'Im Tresor speichern',
    'btn.copy_link': 'Link kopieren',
    'btn.continue_with': 'Mit weiterem Werkzeug bearbeiten',
    'status.processed_locally': 'Lokal auf Ihrem Gerät verarbeitet',
    'status.ready_download': 'Ihre PDF-Datei wurde erfolgreich verarbeitet!',
    'footer.disclaimer': 'Datenschutz garantiert.',
  },
  it: {
    'nav.all_tools': 'Tutti gli strumenti PDF',
    'nav.merge': 'Unisci PDF',
    'nav.split': 'Dividi PDF',
    'nav.compress': 'Comprimi PDF',
    'nav.convert': 'Converti PDF',
    'nav.edit_sign': 'Modifica e Firma',
    'nav.security': 'Sicurezza',
    'nav.history': 'Cronologia',
    'nav.vault': 'Cloud Vault',
    'nav.login': 'Accedi',
    'nav.signup': 'Registrati',
    'hero.title': 'Tutti gli strumenti per i tuoi PDF in un unico posto',
    'hero.subtitle': 'Strumenti PDF 100% gratuiti e facili da usare.',
    'hero.privacy_note': '🔒 Massima privacy: elaborazione locale nel browser.',
    'hero.search_placeholder': 'Cerca uno strumento PDF...',
    'category.all': 'Tutti gli strumenti',
    'category.organize': 'Organizza PDF',
    'category.optimize': 'Ottimizza',
    'category.convert_to': 'Converti in PDF',
    'category.convert_from': 'Converti da PDF',
    'category.edit_sign': 'Modifica & Firma',
    'category.security': 'Sicurezza PDF',
    'btn.select_files': 'Seleziona file PDF',
    'btn.select_images': 'Seleziona immagini',
    'btn.drop_files': 'o trascina qui i PDF',
    'btn.sample_pdf': 'Prova con PDF di esempio',
    'btn.download': 'Scarica PDF',
    'btn.download_zip': 'Scarica ZIP',
    'btn.save_vault': 'Salva nel Vault',
    'btn.copy_link': 'Copia link',
    'btn.continue_with': 'Continua con un altro strumento',
    'status.processed_locally': 'Elaborato sul tuo dispositivo',
    'status.ready_download': 'Il tuo PDF è stato elaborato con successo!',
    'footer.disclaimer': 'La tua privacy è al sicuro.',
  },
  pt: {
    'nav.all_tools': 'Todas as ferramentas PDF',
    'nav.merge': 'Juntar PDF',
    'nav.split': 'Dividir PDF',
    'nav.compress': 'Comprimir PDF',
    'nav.convert': 'Converter PDF',
    'nav.edit_sign': 'Editar e Assinar',
    'nav.security': 'Segurança',
    'nav.history': 'Histórico',
    'nav.vault': 'Cofre Cloud',
    'nav.login': 'Entrar',
    'nav.signup': 'Cadastrar',
    'hero.title': 'Todas as ferramentas PDF em um só lugar',
    'hero.subtitle': 'Ferramentas PDF 100% gratuitas e fáceis de usar.',
    'hero.privacy_note': '🔒 Privacidade total: processado no seu navegador.',
    'hero.search_placeholder': 'Buscar ferramenta PDF...',
    'category.all': 'Todas as ferramentas',
    'category.organize': 'Organizar PDF',
    'category.optimize': 'Otimizar',
    'category.convert_to': 'Converter para PDF',
    'category.convert_from': 'Converter de PDF',
    'category.edit_sign': 'Editar & Assinar',
    'category.security': 'Segurança PDF',
    'btn.select_files': 'Selecionar arquivos PDF',
    'btn.select_images': 'Selecionar imagens',
    'btn.drop_files': 'ou solte os arquivos aqui',
    'btn.sample_pdf': 'Testar com PDF de exemplo',
    'btn.download': 'Baixar PDF',
    'btn.download_zip': 'Baixar ZIP',
    'btn.save_vault': 'Salvar no Cofre',
    'btn.copy_link': 'Copiar link',
    'btn.continue_with': 'Continuar em outra ferramenta',
    'status.processed_locally': 'Processado localmente no seu dispositivo',
    'status.ready_download': 'Seu arquivo PDF foi processado com sucesso!',
    'footer.disclaimer': 'Privacidade em primeiro lugar.',
  },
  ja: {
    'nav.all_tools': 'すべてのPDFツール',
    'nav.merge': 'PDF 結合',
    'nav.split': 'PDF 分割',
    'nav.compress': 'PDF 圧縮',
    'nav.convert': 'PDF 変換',
    'nav.edit_sign': '編集・電子署名',
    'nav.security': 'セキュリティ',
    'nav.history': '処理履歴',
    'nav.vault': 'クラウド保管庫',
    'nav.login': 'ログイン',
    'nav.signup': '登録',
    'hero.title': 'PDF作業に必要なすべてのツールがここに',
    'hero.subtitle': 'すべて無料、誰でも簡単操作。結合、分割、圧縮、変換、署名までワンクリック。',
    'hero.privacy_note': '🔒 100% ブラウザ内ローカル処理：ファイルは外部サーバーに送信されません。',
    'hero.search_placeholder': 'PDFツールを検索 (例: 結合, 圧縮, 署名)...',
    'category.all': '全ツール',
    'category.organize': 'PDF 整理',
    'category.optimize': '最適化・圧縮',
    'category.convert_to': 'PDFに変換',
    'category.convert_from': 'PDFから変換',
    'category.edit_sign': '編集と署名',
    'category.security': 'PDF セキュリティ',
    'btn.select_files': 'PDFファイルを選択',
    'btn.select_images': '画像を選択',
    'btn.drop_files': 'またはここにPDFをドロップ',
    'btn.sample_pdf': 'サンプルPDFで今すぐ試す',
    'btn.download': 'PDFをダウンロード',
    'btn.download_zip': 'ZIPをダウンロード',
    'btn.save_vault': 'クラウドに保存',
    'btn.copy_link': 'リンクをコピー',
    'btn.continue_with': '別のツールで続けて編集',
    'status.processed_locally': 'お使いの端末で安全に処理されました',
    'status.ready_download': 'PDFの処理が完了しました！',
    'footer.disclaimer': 'プライバシー保護: ファイルは保持されません。',
  },
  zh: {
    'nav.all_tools': '所有PDF工具',
    'nav.merge': '合并 PDF',
    'nav.split': '拆分 PDF',
    'nav.compress': '压缩 PDF',
    'nav.convert': '转换 PDF',
    'nav.edit_sign': '编辑与签名',
    'nav.security': '安全与权限',
    'nav.history': '处理历史',
    'nav.vault': '云端文件库',
    'nav.login': '登录',
    'nav.signup': '注册',
    'hero.title': '一站式处理PDF所需的所有工具',
    'hero.subtitle': '100%免费且易于使用的PDF工具。只需点击几下即可合并、拆分、压缩、转换、旋转和签名PDF。',
    'hero.privacy_note': '🔒 100% 本地浏览器安全处理：您的文件不会泄露。',
    'hero.search_placeholder': '搜索PDF工具（例如合并、压缩、签名、水印）...',
    'category.all': '全部工具',
    'category.organize': '组织管理',
    'category.optimize': '优化压缩',
    'category.convert_to': '转换为PDF',
    'category.convert_from': '从PDF转换',
    'category.edit_sign': '编辑与签名',
    'category.security': 'PDF安全',
    'btn.select_files': '选择 PDF 文件',
    'btn.select_images': '选择图片',
    'btn.drop_files': '或将文件拖放到此处',
    'btn.sample_pdf': '使用示例PDF即刻测试',
    'btn.download': '下载 PDF',
    'btn.download_zip': '下载 ZIP 压缩包',
    'btn.save_vault': '保存到云端文件库',
    'btn.copy_link': '复制分享链接',
    'btn.continue_with': '使用其他工具继续处理',
    'status.processed_locally': '已在您的本地设备上安全处理',
    'status.ready_download': '您的PDF文件已成功处理完毕！',
    'footer.disclaimer': '隐私第一：您的文档不会被存储或泄露。',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('ilovepdf_lang') as LanguageCode;
    return saved && translations[saved] ? saved : 'en';
  });

  const setLang = (newLang: LanguageCode) => {
    setLangState(newLang);
    localStorage.setItem('ilovepdf_lang', newLang);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
