import type { ToolItem, ToolCategory } from '../types';

export const TOOLS: ToolItem[] = [
  // Organize
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    shortDesc: 'Combine PDFs in the order you want with the easiest PDF merger available.',
    category: 'organize',
    iconName: 'Layers',
    color: '#e5322d',
    bgLight: 'bg-red-50 text-red-600',
    accentBorder: 'hover:border-red-500',
    route: '/merge-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    multiFile: true,
    popular: true,
    instructions: [
      'Select or drag & drop multiple PDF files from your device.',
      'Drag and drop the thumbnails or use the arrow buttons to arrange pages in your preferred order.',
      'Click "Merge PDF" to combine all files into one seamless document.',
    ],
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    shortDesc: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    category: 'organize',
    iconName: 'Scissors',
    color: '#e5322d',
    bgLight: 'bg-red-50 text-red-600',
    accentBorder: 'hover:border-red-500',
    route: '/split-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    popular: true,
    instructions: [
      'Upload a multi-page PDF document.',
      'Choose custom page ranges (e.g., 1-3, 5, 8-10) or extract every single page into a ZIP archive.',
      'Click "Split PDF" to generate and download your split documents.',
    ],
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    shortDesc: 'Sort, add and delete PDF pages. Drag and drop the page thumbnails and sort them.',
    category: 'organize',
    iconName: 'LayoutGrid',
    color: '#e5322d',
    bgLight: 'bg-red-50 text-red-600',
    accentBorder: 'hover:border-red-500',
    route: '/organize-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    popular: true,
    instructions: [
      'Upload your PDF document to load the interactive page organizer.',
      'Rearrange pages by dragging them, click trash to delete, rotate individual pages, or insert blank pages.',
      'Save your freshly organized PDF.',
    ],
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    shortDesc: 'Rotate your PDF pages just the way you need. Rotate multiple PDFs at the same time!',
    category: 'organize',
    iconName: 'RotateCw',
    color: '#e5322d',
    bgLight: 'bg-red-50 text-red-600',
    accentBorder: 'hover:border-red-500',
    route: '/rotate-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    instructions: [
      'Upload the PDF you want to rotate.',
      'Rotate all pages 90° right, 90° left, or 180°, or rotate individual pages independently.',
      'Apply rotations and download the updated PDF.',
    ],
  },

  // Optimize
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    shortDesc: 'Reduce file size while optimizing for maximal PDF quality.',
    category: 'optimize',
    iconName: 'Minimize2',
    color: '#10b981',
    bgLight: 'bg-emerald-50 text-emerald-600',
    accentBorder: 'hover:border-emerald-500',
    route: '/compress-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    popular: true,
    instructions: [
      'Select your heavy PDF document.',
      'Choose your compression level: Extreme, Recommended (Best balance), or Less compression.',
      'Click "Compress PDF" to reduce byte weight and see live savings statistics.',
    ],
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    shortDesc: 'Repair damaged and corrupt PDF files. Recover content and structural data.',
    category: 'optimize',
    iconName: 'Wrench',
    color: '#10b981',
    bgLight: 'bg-emerald-50 text-emerald-600',
    accentBorder: 'hover:border-emerald-500',
    route: '/repair-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    instructions: [
      'Upload a damaged, corrupted, or unreadable PDF.',
      'Our engine re-indexes the cross-reference table and fixes object streams.',
      'Download the repaired, clean document.',
    ],
  },

  // Convert to PDF
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    shortDesc: 'Convert JPG, PNG, WebP images to PDF. Adjust orientation, margins, and page sizes.',
    category: 'convert-to',
    iconName: 'Image',
    color: '#3b82f6',
    bgLight: 'bg-blue-50 text-blue-600',
    accentBorder: 'hover:border-blue-500',
    route: '/jpg-to-pdf',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'pdf',
    executionMode: 'client',
    multiFile: true,
    popular: true,
    instructions: [
      'Upload one or more images (JPG, PNG, WebP).',
      'Reorder images, select page orientation (Portrait/Landscape), and set page margins.',
      'Click "Convert to PDF" to generate a crisp document.',
    ],
  },
  {
    id: 'text-to-pdf',
    name: 'Text to PDF',
    shortDesc: 'Convert plain text, markdown, and articles to formatted PDF documents.',
    category: 'convert-to',
    iconName: 'FileText',
    color: '#3b82f6',
    bgLight: 'bg-blue-50 text-blue-600',
    accentBorder: 'hover:border-blue-500',
    route: '/text-to-pdf',
    acceptedFormats: ['.txt', '.md'],
    outputFormat: 'pdf',
    executionMode: 'client',
    instructions: [
      'Type or paste your text, or upload a .txt / .md file.',
      'Customize font, line spacing, margins, and header options.',
      'Click "Generate PDF" to download.',
    ],
  },

  // Convert from PDF
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    shortDesc: 'Extract all pages in a PDF to high-quality JPG or PNG images or download as ZIP.',
    category: 'convert-from',
    iconName: 'FileImage',
    color: '#f59e0b',
    bgLight: 'bg-amber-50 text-amber-600',
    accentBorder: 'hover:border-amber-500',
    route: '/pdf-to-jpg',
    acceptedFormats: ['.pdf'],
    outputFormat: 'zip',
    executionMode: 'client',
    popular: true,
    instructions: [
      'Select the PDF file you wish to convert into pictures.',
      'Choose image format (JPG or PNG) and image quality (Normal 150 DPI or Ultra 300 DPI).',
      'Download individual page images or a complete ZIP package.',
    ],
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    shortDesc: 'Extract clean selectable text content from your PDF documents.',
    category: 'convert-from',
    iconName: 'FileCode',
    color: '#f59e0b',
    bgLight: 'bg-amber-50 text-amber-600',
    accentBorder: 'hover:border-amber-500',
    route: '/pdf-to-text',
    acceptedFormats: ['.pdf'],
    outputFormat: 'txt',
    executionMode: 'client',
    instructions: [
      'Upload any text-based PDF file.',
      'Extract text with paragraph formatting preserved.',
      'Copy to clipboard or download as .txt / .docx file.',
    ],
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    shortDesc: 'Optical Character Recognition: extract text from scanned documents & image PDFs.',
    category: 'convert-from',
    iconName: 'ScanText',
    color: '#f59e0b',
    bgLight: 'bg-amber-50 text-amber-600',
    accentBorder: 'hover:border-amber-500',
    route: '/ocr-pdf',
    acceptedFormats: ['.pdf', '.jpg', '.png'],
    outputFormat: 'txt',
    executionMode: 'client',
    instructions: [
      'Upload a scanned PDF or photo containing text.',
      'Select document language (English, Spanish, French, German, etc.).',
      'Our client-side OCR engine recognizes text and generates editable output.',
    ],
  },

  // Edit & Sign
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    shortDesc: 'Add text, shapes, comments, highlights, drawings, and images to your PDF.',
    category: 'edit-sign',
    iconName: 'PenTool',
    color: '#8b5cf6',
    bgLight: 'bg-purple-50 text-purple-600',
    accentBorder: 'hover:border-purple-500',
    route: '/edit-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    popular: true,
    instructions: [
      'Upload the PDF you want to annotate and edit.',
      'Use the top toolbar to insert text boxes, draw freehand, highlight lines, add shapes, or place images.',
      'Save your edited PDF with high fidelity.',
    ],
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    shortDesc: 'Sign yourself or request electronic signatures. Draw, type, or upload your signature.',
    category: 'edit-sign',
    iconName: 'FileSignature',
    color: '#8b5cf6',
    bgLight: 'bg-purple-50 text-purple-600',
    accentBorder: 'hover:border-purple-500',
    route: '/sign-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    popular: true,
    instructions: [
      'Upload the document that requires signing.',
      'Draw your signature with smooth pen smoothing, type with cursive font styles, or upload your signature stamp.',
      'Position and resize your signature on the designated page and click "Sign Document".',
    ],
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    shortDesc: 'Stamp an image or text over your PDF. Choose typography, transparency and position.',
    category: 'edit-sign',
    iconName: 'Stamp',
    color: '#8b5cf6',
    bgLight: 'bg-purple-50 text-purple-600',
    accentBorder: 'hover:border-purple-500',
    route: '/watermark-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    popular: true,
    instructions: [
      'Select your PDF document.',
      'Choose text watermark (e.g., CONFIDENTIAL, DRAFT) or upload your company logo.',
      'Customize position (9-point grid), angle (45°), opacity, font size, and color, then download.',
    ],
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    shortDesc: 'Add page numbers into PDFs with ease. Choose position, dimensions, typography.',
    category: 'edit-sign',
    iconName: 'ListOrdered',
    color: '#8b5cf6',
    bgLight: 'bg-purple-50 text-purple-600',
    accentBorder: 'hover:border-purple-500',
    route: '/page-numbers',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    instructions: [
      'Upload the document to number.',
      'Select layout position (Bottom Right, Bottom Center, Top Center), format ("Page 1 of N" or "1"), and margins.',
      'Click "Add Page Numbers" to generate numbered document.',
    ],
  },
  {
    id: 'add-text',
    name: 'Add Text to PDF',
    shortDesc: 'Quickly insert notes, headers, dates, and text labels onto any page of your PDF.',
    category: 'edit-sign',
    iconName: 'Type',
    color: '#8b5cf6',
    bgLight: 'bg-purple-50 text-purple-600',
    accentBorder: 'hover:border-purple-500',
    route: '/add-text',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    instructions: [
      'Upload your PDF file.',
      'Click on any area to place a text box, type your notes, choose font size & color.',
      'Export the updated PDF.',
    ],
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    shortDesc: 'Crop PDF page margins, trim white borders, or select specific content regions.',
    category: 'edit-sign',
    iconName: 'Crop',
    color: '#8b5cf6',
    bgLight: 'bg-purple-50 text-purple-600',
    accentBorder: 'hover:border-purple-500',
    route: '/crop-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    instructions: [
      'Upload the PDF document.',
      'Drag the visual crop boundary on screen or choose standard aspect ratio margins.',
      'Apply the crop to all pages or selected pages.',
    ],
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    shortDesc: 'Permanently black-out and sanitize sensitive text, numbers, and private data.',
    category: 'security',
    iconName: 'EyeOff',
    color: '#dc2626',
    bgLight: 'bg-red-50 text-red-600',
    accentBorder: 'hover:border-red-500',
    route: '/redact-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    instructions: [
      'Upload your confidential PDF.',
      'Draw black-out redaction boxes over sensitive personal information or financial data.',
      'Permanently rasterize the redacted zones so text cannot be highlighted or recovered.',
    ],
  },

  // Security
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    shortDesc: 'Encrypt your PDF with a secure password and prevent unauthorized reading.',
    category: 'security',
    iconName: 'Lock',
    color: '#dc2626',
    bgLight: 'bg-red-50 text-red-600',
    accentBorder: 'hover:border-red-500',
    route: '/protect-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    popular: true,
    instructions: [
      'Upload the PDF document you wish to secure.',
      'Enter and confirm a strong password.',
      'Click "Protect PDF" to encrypt the file.',
    ],
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    shortDesc: 'Remove PDF password security, giving you the freedom to use your PDFs as you want.',
    category: 'security',
    iconName: 'Unlock',
    color: '#dc2626',
    bgLight: 'bg-red-50 text-red-600',
    accentBorder: 'hover:border-red-500',
    route: '/unlock-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    instructions: [
      'Upload a password-protected PDF file.',
      'Enter the owner password to remove security protection.',
      'Download your unlocked, open PDF document.',
    ],
  },
  {
    id: 'metadata-editor',
    name: 'Metadata Editor',
    shortDesc: 'View, edit, or sanitize document metadata: Title, Author, Subject, Keywords, Creator.',
    category: 'security',
    iconName: 'Sliders',
    color: '#dc2626',
    bgLight: 'bg-red-50 text-red-600',
    accentBorder: 'hover:border-red-500',
    route: '/metadata-editor',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    executionMode: 'client',
    instructions: [
      'Upload your PDF file to inspect its internal metadata properties.',
      'Update Title, Author, Subject, Keywords, or clear all metadata for privacy.',
      'Save the clean document.',
    ],
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDF',
    shortDesc: 'Side-by-side visual diff comparison between two versions of a PDF document.',
    category: 'security',
    iconName: 'SplitSquareVertical',
    color: '#dc2626',
    bgLight: 'bg-red-50 text-red-600',
    accentBorder: 'hover:border-red-500',
    route: '/compare-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'view',
    executionMode: 'client',
    instructions: [
      'Upload the original PDF version and the modified PDF version.',
      'Use the split-screen viewer with synchronized scrolling to spot revisions.',
      'Highlight page differences visually.',
    ],
  },
];

export const CATEGORIES: { id: ToolCategory; labelKey: string; icon: string }[] = [
  { id: 'all', labelKey: 'category.all', icon: 'Grid' },
  { id: 'organize', labelKey: 'category.organize', icon: 'Layers' },
  { id: 'optimize', labelKey: 'category.optimize', icon: 'Minimize2' },
  { id: 'convert-to', labelKey: 'category.convert_to', icon: 'ArrowRightCircle' },
  { id: 'convert-from', labelKey: 'category.convert_from', icon: 'ArrowLeftCircle' },
  { id: 'edit-sign', labelKey: 'category.edit_sign', icon: 'PenTool' },
  { id: 'security', labelKey: 'category.security', icon: 'ShieldCheck' },
];

export function getToolById(id: string): ToolItem | undefined {
  return TOOLS.find((t) => t.id === id);
}
